export const ADD_TASK = 'ADD_TASK';
export const INPUT_TYPING = 'INPUT_TYPING';
export const REMOVE_TASK = 'REMOVE_TASK';
export const EDIT_SELECTED_STATUS = 'EDIT_SELECTED_STATUS';
export const RM_ALL = 'RM_ALL';
export const TASK_STATUS_COMPLETE = 'TASK_STATUS_COMPLETE';
export const TASK_STATUS_INCOMPLETE = 'TASK_STATUS_INCOMPLETE';